### ISSUE TITLE
Script don't appears - aitextgen required

### ISSUE THREAD

**Issue by corbettaluigi** [Spaceginner/MagicPrompt-awebui#1]
I think the problem is:
ModuleNotFoundError: No module named 'aitextgen'

**Comment by nulqwy** [comment]
you need to run command
```
pip install aitextgen
```

**Comment by nulqwy** [comment]
i will add autoinstallation of this module, when will refactor code.

**Comment by nulqwy** [comment]
my fault. i didnt write installation section proparly. @corbettaluigi reread it

**Comment by nulqwy** [comment]
did u resolve your issue?

**Comment by corbettaluigi** [comment]
no. I had already tried installing the aitextgen module as you suggested, but I think it is a problem with that module on my pc, because I can't import it even in a 'clean' python script (import aitextgen -> ImportError: cannot import name '_TPU_AVAILABLE' from 'pytorch_lightning.utilities')

**Comment by nulqwy** [comment]
did you re-read installation steps (i changed them as they were not full)? In particular 4 to 6 steps.

**Comment by corbettaluigi** [comment]
yes, it works, thks

**Comment by nulqwy** [comment]
No problems, my fault. If no questions (related ones) left, close issue.
